[versions]
grgit = "5.2.2"
jgit = "6.9.0.202403050737-r"
mockk = "1.13.10"

[libraries]
grgit-core = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
sonarqube = { id = "org.sonarqube", version = "4.4.1.3373" }
versioning = { id = "net.nemerosa.versioning", version = "3.1.0" }
